table Dim_Calendario
	lineageTag: f00bfba2-ce3a-4ead-a15b-aa0c500c54a1

	column Fecha
		dataType: dateTime
		formatString: Long Date
		lineageTag: f01b85fb-c1bf-4ad7-8871-1fb293ab1762
		summarizeBy: none
		sourceColumn: Fecha

		variation Variación
			isDefault
			relationship: d3d306be-771f-4abc-8f8a-21b87ff8e06c
			defaultHierarchy: LocalDateTable_5ff8363a-d591-4155-b10d-61782b56ba5b.'Jerarquía de fechas'

		annotation SummarizationSetBy = Automatic

		annotation UnderlyingDateTimeDataType = Date

	column Año
		dataType: int64
		formatString: 0
		lineageTag: 34ecb368-7a28-4025-a781-57eb5f135db7
		summarizeBy: sum
		sourceColumn: Año

		annotation SummarizationSetBy = Automatic

	column Semana
		dataType: int64
		formatString: 0
		lineageTag: a7d1c2c8-74bc-43f3-996d-59a0d30db784
		summarizeBy: sum
		sourceColumn: Semana

		annotation SummarizationSetBy = Automatic

	column Mes
		dataType: string
		lineageTag: eabedba3-a18e-40d1-b5a1-9ce74fb639e3
		summarizeBy: none
		sourceColumn: Mes

		annotation SummarizationSetBy = Automatic

	column 'Numero Mes'
		dataType: int64
		formatString: 0
		lineageTag: 99c7b969-5ce9-4568-9986-f6c6b28a33db
		summarizeBy: sum
		sourceColumn: Numero Mes

		annotation SummarizationSetBy = Automatic

	column datekey
		dataType: int64
		formatString: 0
		lineageTag: ea81d825-a775-41d9-92ef-17dffe262ba9
		summarizeBy: none
		sourceColumn: datekey

		annotation SummarizationSetBy = Automatic

	partition Dim_Calendario = m
		mode: import
		source =
				let
				    Origen = Excel.Workbook(File.Contents("C:\Users\David\Documents\UCA\BI\VentasVehiculos.xlsx"), null, true),
				    Dim_Calendario_Table = Origen{[Item="Dim_Calendario",Kind="Table"]}[Data],
				    #"Tipo cambiado" = Table.TransformColumnTypes(Dim_Calendario_Table,{{"Fecha", type date}, {"Año", Int64.Type}, {"Semana", Int64.Type}, {"Mes", type text}, {"Numero Mes", Int64.Type}, {"datekey", Int64.Type}})
				in
				    #"Tipo cambiado"

	annotation PBI_NavigationStepName = Navegación

	annotation PBI_ResultType = Table

