table Dim_Cliente
	lineageTag: 9f174c73-1182-4cc8-a97b-7141f6c0f595

	column id_Cliente
		dataType: int64
		formatString: 0
		lineageTag: a4b3f6ba-1af4-4491-822e-d09c3c32b844
		summarizeBy: none
		sourceColumn: id_Cliente

		annotation SummarizationSetBy = Automatic

	column Nombre
		dataType: string
		lineageTag: efa0e5ef-865d-46b0-b76b-1603b22e034e
		summarizeBy: none
		sourceColumn: Nombre

		annotation SummarizationSetBy = Automatic

	partition Dim_Cliente = m
		mode: import
		source =
				let
				    Origen = Excel.Workbook(File.Contents("C:\Users\David\Documents\UCA\BI\VentasVehiculos.xlsx"), null, true),
				    Dim_Cliente_Table = Origen{[Item="Dim_Cliente",Kind="Table"]}[Data],
				    #"Tipo cambiado" = Table.TransformColumnTypes(Dim_Cliente_Table,{{"id_Cliente", Int64.Type}, {"Nombre", type text}})
				in
				    #"Tipo cambiado"

	annotation PBI_NavigationStepName = Navegación

	annotation PBI_ResultType = Table

